<!DOCTYPE tiles-definitions
    [
        <!ELEMENT component-definitions (definition+)>
        <!ELEMENT tiles-definitions (definition+)>
        <!ELEMENT definition (put*, putList*)>
        <!ATTLIST definition
            name CDATA #REQUIRED
            page CDATA #IMPLIED
            path CDATA #IMPLIED
            extends CDATA #IMPLIED
            role CDATA #IMPLIED
            template CDATA #IMPLIED
            controllerClass CDATA #IMPLIED
            controllerUrl CDATA #IMPLIED>
        <!ELEMENT put (#PCDATA)>
        <!ATTLIST put
            name CDATA #REQUIRED
            value CDATA #IMPLIED
            type (string | page | template | definition) #IMPLIED
            content CDATA #IMPLIED
            direct (true | false) #IMPLIED>
        <!ELEMENT putList ( (add* | item* | bean* | putList*)+) >
        <!ATTLIST putList
            name CDATA #REQUIRED>
        <!ELEMENT putListElements (add | item | bean)>
        <!ELEMENT add (#PCDATA)>
        <!ATTLIST add
            value CDATA #IMPLIED
            type (string | page | template | definition) #IMPLIED
            content CDATA #IMPLIED
            direct (true | false) #IMPLIED>
        <!ELEMENT bean (#PCDATA)>
        <!ATTLIST bean
            classtype CDATA #REQUIRED>
        <!ELEMENT item (#PCDATA)>
        <!ATTLIST item
            value CDATA #REQUIRED
            link CDATA #REQUIRED
            classtype CDATA #IMPLIED
            icon CDATA #IMPLIED
            tooltip CDATA #IMPLIED>
    ]>

<tiles-definitions>
    <definition name="layout.example" path="/template/template.jsp" >
        <put name="header" value="/common/header.jsp" />
        <put name="menu" value="/common/navigation.jsp" />
    </definition>


    <definition name="/registration.tiles" extends="layout.example" >
        <put name="body" value="/registration.jsp" />
    </definition>

    <definition name="/userlist.tiles" extends="layout.example" >
        <put name="body" value="/userlist.jsp" />
    </definition>

    <definition name="/login.tiles" extends="layout.example" >
        <put name="body" value="/login.jsp" />
    </definition>

    <definition name="/blogger/bloggerofferlist.tiles" extends="layout.example" >
        <put name="body" value="/blogger/bloggerofferlist.jsp" />
    </definition>

    <definition name="/blogger/bloggerofferdetail.tiles" extends="layout.example" >
        <put name="body" value="/blogger/bloggerofferdetail.jsp" />
    </definition>

    <definition name="/blogger/index.tiles" extends="layout.example" >
        <put name="body" value="/blogger/index.jsp" />
    </definition>

    <definition name="/blogger/earnings.tiles" extends="layout.example" >
        <put name="body" value="/blogger/earnings.jsp" />
    </definition>

    <definition name="/researcher/index.tiles" extends="layout.example" >
        <put name="body" value="/researcher/index.jsp" />
    </definition>

    <definition name="/researcher/researcherofferlist.tiles" extends="layout.example" >
        <put name="body" value="/researcher/researcherofferlist.jsp" />
    </definition>

    <definition name="/researcher/newoffer.tiles" extends="layout.example" >
        <put name="body" value="/researcher/newoffer.jsp" />
    </definition>

    <definition name="/registration-success.tiles" extends="layout.example" >
        <put name="body" value="/registration-success.jsp" />
    </definition>

    <definition name="/index.tiles" extends="layout.example" >
        <put name="body" value="/index.jsp" />
    </definition>

    


</tiles-definitions>
